name: Merge master to dev
on:
  push:
    branches: [ master ]
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Set credentials
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: Fetch
      run: |
        git fetch master
        git fetch dev
    - name: Merge
      run: |
        git checkout dev
        git merge master
    - name: Puch
      run: |
        git push origin dev
